import { OtaPackage } from "@/types/ota";

export const DEFAULT_OTA_PACKAGES: OtaPackage[] = [
  {
    id: "OTA-PKG-001",
    title: "Cancún & Riviera Maya All Inclusive",
    destination: "Cancún",
    country: "México",
    region: "Internacional",
    type: "paquete",
    providerType: "mayorista",
    operatorName: "Juliá Tours",
    durationDays: 8,
    durationNights: 7,
    departureDates: ["12 Nov 2026", "03 Dic 2026", "15 Ene 2027"],
    departureOrigin: "Buenos Aires (Ezeiza)",
    transportType: "Aéreo",
    airline: "Copa Airlines",
    hotelName: "Riu Tequila 5★ Resort",
    hotelStars: 5,
    foodPlan: "All Inclusive",
    priceArs: 2850000,
    priceUsd: 2150,
    installments: "Hasta 6 cuotas fijas",
    rewardsPointsEarned: 850,
    badge: "🌴 ALL INCLUSIVE 5★",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85",
    description: "Viví unas vacaciones soñadas en el Caribe mexicano con aéreos directos, traslados privados y régimen All Inclusive en resort de primera línea.",
    includedServices: [
      "Vuelos ida y vuelta con equipaje en bodega",
      "Traslados in/out en van ejecutiva",
      "7 noches All Inclusive 24hs",
      "Acceso ilimitado a restaurantes temáticos",
      "Asistencia al viajero internacional"
    ],
    itinerarySummary: [
      { day: 1, title: "Llegada al paraíso", description: "Vuelo internacional, recepción y check-in en resort de Cancún." },
      { day: 2, title: "Día de playa y relax", description: "Disfrute de playas privadas, deportes acuáticos y gastronomía gourmet." },
      { day: 5, title: "Excursión a Chichén Itzá (Opcional)", description: "Visita a una de las 7 maravillas del mundo moderno." },
      { day: 8, title: "Regreso", description: "Check-out, traslado a aeropuerto y vuelo de regreso." }
    ],
    featured: true
  },
  {
    id: "OTA-PKG-002",
    title: "Bariloche Mágico & Circuito Chico",
    destination: "Bariloche",
    country: "Argentina",
    region: "Nacional",
    type: "salida_grupal",
    providerType: "propio",
    operatorName: "TravelApp Exclusivo",
    durationDays: 6,
    durationNights: 5,
    departureDates: ["20 Oct 2026", "10 Nov 2026", "08 Dic 2026"],
    departureOrigin: "Tucumán / Buenos Aires",
    transportType: "Aéreo",
    airline: "Aerolíneas Argentinas",
    hotelName: "Hotel Edelweiss 4★",
    hotelStars: 4,
    foodPlan: "Media Pensión",
    priceArs: 980000,
    priceUsd: 740,
    installments: "Hasta 12 cuotas fijas",
    rewardsPointsEarned: 450,
    badge: "⭐ SALIDA PROPIA ACOMPAÑADA",
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=85",
    description: "Salida grupal exclusiva con coordinador permanente TravelApp. Navegación por el Lago Nahuel Huapi, Cerro Campanario y degustación de chocolates artesanales.",
    includedServices: [
      "Aéreos ida y vuelta desde Tucumán o BUE",
      "5 noches de alojamiento en hotel céntrico 4★",
      "Media pensión (desayunos y cenas con bebidas)",
      "Circuito Chico y Punto Panorámico",
      "Coordinador permanente desde el origen"
    ],
    featured: true
  },
  {
    id: "OTA-PKG-003",
    title: "Crucero Costa: Río de Janeiro, Ilhabela & Punta del Este",
    destination: "Costas de Brasil y Uruguay",
    country: "Brasil / Uruguay",
    region: "Internacional",
    type: "crucero",
    providerType: "mayorista",
    operatorName: "Costa Cruceros / Ola",
    durationDays: 9,
    durationNights: 8,
    departureDates: ["14 Dic 2026", "04 Ene 2027", "22 Feb 2027"],
    departureOrigin: "Puerto de Buenos Aires",
    transportType: "Crucero",
    hotelName: "Buque Costa Fascinosa (Cabina Externa con Balcón)",
    hotelStars: 5,
    foodPlan: "Pensión Completa",
    priceArs: 2450000,
    priceUsd: 1850,
    installments: "Hasta 6 cuotas en USD o ARS",
    rewardsPointsEarned: 700,
    badge: "🚢 CRUCERO EXCLUSIVO 2026/27",
    imageUrl: "https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=1200&q=85",
    description: "Embarcate en Buenos Aires y navegá hacia las mejores playas de Brasil y el glamour de Punta del Este con espectáculos estilo Broadway todas las noches.",
    includedServices: [
      "8 noches de crucero en cabina seleccionada",
      "Todas las comidas en restaurantes principales y buffet",
      "Espectáculos teatrales, discoteca y casino",
      "Tasas portuarias y propinas incluidas",
      "Actividades y animación a bordo para todas las edades"
    ],
    featured: true
  },
  {
    id: "OTA-PKG-004",
    title: "Cataratas del Iguazú & Selva Misionera",
    destination: "Puerto Iguazú",
    country: "Argentina",
    region: "Nacional",
    type: "escapada",
    providerType: "propio",
    operatorName: "TravelApp Exclusivo",
    durationDays: 4,
    durationNights: 3,
    departureDates: ["Semanal (Jueves a Domingo)"],
    departureOrigin: "Buenos Aires / Córdoba / Tucumán",
    transportType: "Aéreo",
    airline: "Flybondi / Aerolíneas",
    hotelName: "Grand Crucero Iguazú Hotel 4★",
    hotelStars: 4,
    foodPlan: "Desayuno",
    priceArs: 580000,
    priceUsd: 440,
    installments: "Hasta 6 cuotas fijas",
    rewardsPointsEarned: 280,
    badge: "🔥 ESCAPADA FIN DE SEMANA",
    imageUrl: "https://images.unsplash.com/photo-1589556264800-08ae9e129a8c?auto=format&fit=crop&w=1200&q=85",
    description: "Viví la imponente fuerza de la Garganta del Diablo con aéreos directos, traslados y excursiones con guías oficiales de Parques Nacionales.",
    includedServices: [
      "Vuelos ida y vuelta con bolso de mano y equipaje",
      "3 noches en hotel con piscina en la selva",
      "Excursión Parque Nacional Iguazú (Lado Argentino)",
      "Excursión Parque Nacional Foz do Iguaçu (Lado Brasilero)",
      "Traslados aeropuerto - hotel - aeropuerto"
    ],
    featured: false
  },
  {
    id: "OTA-PKG-005",
    title: "Madrid, París & Roma: Europa Clásica",
    destination: "Europa Multidestino",
    country: "España / Francia / Italia",
    region: "Internacional",
    type: "paquete",
    providerType: "mayorista",
    operatorName: "Dertour / TipGroup",
    durationDays: 16,
    durationNights: 14,
    departureDates: ["10 May 2027", "15 Jun 2027", "08 Sep 2027"],
    departureOrigin: "Buenos Aires (Ezeiza)",
    transportType: "Aéreo",
    airline: "Iberia / Air Europa",
    hotelName: "Hoteles 4★ céntricos seleccionados",
    hotelStars: 4,
    foodPlan: "Desayuno",
    priceArs: 5200000,
    priceUsd: 3950,
    installments: "Financiación bancaria disponible",
    rewardsPointsEarned: 1500,
    badge: "👑 CIRCUITO EUROPEO SOÑADO",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=85",
    description: "El gran viaje de tu vida: España, Francia e Italia en circuito guiado en español de máxima categoría con trenes de alta velocidad y entradas incluidas.",
    includedServices: [
      "Vuelos intercontinentales ida y vuelta",
      "14 noches en hoteles 4★ con desayuno buffet",
      "Autobús de lujo con guía acompañante en español",
      "Tren de alta velocidad París - Milán/Roma",
      "Visitas panorámicas en Madrid, París, Florencia y Roma"
    ],
    featured: true
  },
  {
    id: "OTA-PKG-006",
    title: "Mendoza & Valle de Uco: Ruta del Vino & Cordillera",
    destination: "Mendoza",
    country: "Argentina",
    region: "Nacional",
    type: "escapada",
    providerType: "propio",
    operatorName: "TravelApp Exclusivo",
    durationDays: 5,
    durationNights: 4,
    departureDates: ["Salidas cada Viernes"],
    departureOrigin: "Buenos Aires / Rosario / Córdoba",
    transportType: "Aéreo",
    airline: "Aerolíneas Argentinas",
    hotelName: "Park Hyatt Mendoza 5★",
    hotelStars: 5,
    foodPlan: "Media Pensión",
    priceArs: 820000,
    priceUsd: 620,
    installments: "Hasta 6 cuotas fijas",
    rewardsPointsEarned: 350,
    badge: "🍷 GOURMET & VINO VIP",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=85",
    description: "Una experiencia enogastronómica inolvidable al pie de la Cordillera de los Andes con almuerzos de 5 pasos en bodegas premiadas a nivel mundial.",
    includedServices: [
      "Vuelos ida y vuelta a Mendoza",
      "4 noches en hotel de categoría con spa",
      "Almuerzo maridado en Bodega Zuccardi o Catena Zapata",
      "Tour Alta Montaña y Puente del Inca",
      "Todos los traslados en minivan ejecutiva"
    ],
    featured: false
  }
];
